title: 05802
description: A personal audio feed
author: 05802
email: my@email.com
lang: en-us
copyright: "&#x2117; &amp; &#xA9; 2020"
logo: /assets/img/logo.png
baseurl: "/rss_audio" # the subpath of your site, e.g. /blog
url: "https://05802.github.io" # the base hostname & protocol for your site, e.g. http://example.com
explicit: "no"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
